name: ppam-terraform-infrastructure-ci

on:
  pull_request:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform-validation:

    name: terraform-validation

    runs-on: ubuntu-latest

    env:
      TFVARS_FILE: environments/ppam-dev.tfvars

    defaults:
      run:
        working-directory: terraform

    steps:

      - name: checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::386620841900:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform format check
        run: terraform fmt -check -recursive

      - name: terraform init
        run: terraform init

#      - name: terraform validate
#        run: terraform validate

#      - name: terraform plan
#        run: terraform plan -input=false -no-color -var-file="$TFVARS_FILE"
